- hosts: all
  roles:
    - common
    
- hosts: personal
  roles:
    - personal

- hosts: servers
  roles: 
    - server

- hosts: web
  roles: 
    - web

- hosts: pi_hole
  roles:
    - pi_hole

- hosts: folding
  roles:
    - folding@home
