- name: Common play for all hosts
  hosts: all
  roles:
    - common

- name: Personal devices
  hosts: personal
  roles:
    - personal

- name: Devices running KDE
  hosts: kde
  roles:
    - kde

- name: Asus Zephyrus devices
  hosts: zephyrus
  roles:
    - zephyrus

- name: Servers
  hosts: servers
  roles:
    - server

- name: Web servers
  hosts: web
  roles:
    - web

- name: Pi-holes
  hosts: pi_hole
  roles:
    - pi_hole

- name: Devices running folding@home
  hosts: folding
  roles:
    - folding@home
