# System vars
hostname: EvanDesktop
timezone: "America/Toronto"

# APT vars
apt_repositories:
  - "ppa:libretro/stable"
apt_packages:
  - libreoffice
  - pavucontrol
  - qbittorrent
  - retroarch
  - rpi-imager
  - solaar
  - steam
  - vlc

# User-level vars
username: ejackson
home_directory: "/home/ejackson"
user_shell: /usr/bin/fish
ssh_key_file: "/home/ejackson/.ssh/id_ed25519"
github_key_file: "/home/ejackson/.ssh/id_github_ed25519"
dotfiles_branch: personal

# SSH config hosts
ssh_config_hosts:
  JacksonBox:
    host: "{{ hostvars['JacksonBox']['hostname'] }}"
    hostname: "{{ hostvars['JacksonBox']['domain'] }}"
  RasperryPi:
    host: "{{ hostvars['RaspberryPi']['hostname'] }}"
    hostname: "{{ hostvars['RaspberryPi']['domain'] }}"

# .deb's
debs:
  vscode:
    url: "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64"
    filename: "/tmp/vscode.deb"
    package: "code"
  wireguird:
    url: "https://github.com/UnnoTed/wireguird/releases/download/v1.1.0/wireguird_amd64.deb"
    filename: "/tmp/wireguird.deb"
    package: "wireguird"
  minecraft:
    url: "https://launcher.mojang.com/download/Minecraft.deb"
    filename: "/tmp/minecraft.deb"
    package: "minecraft-launcher"
  discord:
    url: "https://discord.com/api/download?platform=linux&format=deb"
    filename: "/tmp/discord.deb"
    package: discord
  filen:
    url: "http://cdn.filen.io/@filen/desktop/release/latest/Filen_linux_amd64.deb"
    filename: "/tmp/filen.deb"
    package: filen
  # TODO protonvpn requires a different process

# Flatpaks
flatpaks:
  - io.gitlab.librewolf-community
  - tv.plex.PlexDesktop
  - com.spotify.Client
  - com.github.tchx84.Flatseal
  - org.DolphinEmu.dolphin-emu
  - net.pcsx2.PCSX2
  - com.brave.Browser

# Autostart
autostart_configs:
  filen:
    filename: "filen.desktop"
    script: |
      #!/usr/bin/env xdg-open 
      [Desktop Entry] 
      Type=Application

# Fonts
nerd_fonts_version: "v3.1.0"
fonts:
  ubuntu_mono:
    url: "https://github.com/ryanoasis/nerd-fonts/releases/download/{{ nerd_fonts_version }}/UbuntuMono.zip"
    filename: "/tmp/UbuntuMono.zip"

# rogauracore
rogauracore_cmd: "rogauracore rainbow_cycle 1; rogauracore brightness 1"
rogauracore_version: "1.6"

# No-login users for owning services
service_users:
  folding:
    name: "folding"
    uid: "1007"
    groups: "folding"
    gid: "1007"
