- name: Install paramiko package with pip (required by community.general.ssh_config)
  become: true
  ansible.builtin.pip:
    name: paramiko

- name: Ensure SSH config file exists
  ansible.builtin.copy:
    dest: "{{ home_directory }}/.ssh/config"
    force: false
    content: ""
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Add references to config file
  community.general.ssh_config:
    user: "{{ username }}"
    host: "{{ item }}"
    hostname: "{{ hostvars[item].ansible_host }}"
    state: present
  with_items: "{{ groups.all }}"
  when: hostvars[item].ansible_host is defined
