- name: Install passlib package with pip (required by ansible.builtin.user)
  become: true
  ansible.builtin.pip:
    name: passlib

- name: Configure main user
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    group: "{{ username }}"
    password: "{{ password | password_hash('sha512') }}"
    shell: "{{ user_shell }}"
    update_password: on_create

- name: Suppress login message (hushlogin) for user
  ansible.builtin.file:
    path: "{{ home_directory }}/.hushlogin"
    mode: 0644
    owner: "{{ username }}"
    group: "{{ username }}"
    modification_time: preserve
    access_time: preserve
    state: touch
